<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName Condition="'$(ScrapMapVariant)' != ''">ScrapMap.$(ScrapMapVariant)</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ScrapMap.Core\ScrapMap.Core.csproj" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4129.50" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\Terrain\*-world.png;Assets\Terrain\*-terrain.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
</Project>
